---
- include: check_vars.yml

- include: download.yml
  when: redis_install_from_source
  tags:
    - download

- include: dependencies.yml
  when: redis_install_from_source
  tags:
    - install

- name: check if inside container
  command: grep -qa container=lxc /proc/1/environ
  register: container_env
  ignore_errors: yes

- name: set fact inside container
  set_fact:
    inside_container: "{% if container_env.rc == 0 %}True{% else %}False{% endif %}"

- include: install.yml
  when: redis_install_from_source
  tags:
    - install

- include: install_from_repo.yml
  when: not redis_install_from_source
  tags:
    - install

- include: server.yml
  when: not redis_sentinel
  tags:
    - config

- include: sentinel.yml
  when: redis_sentinel
  tags:
    - config

- include: local_facts.yml
  when: redis_local_facts|bool
